import Foundation
import Hummingbird

struct APIUserInfo: Equatable, Hashable, Codable, ResponseCodable, Sendable {
	var _id: String
	var firebaseAuthId: String
	var name: String
	var username: String
	var avatarURL: URL
	var avatarBlurHash: String?
	var createdAt: Date
	var birthday: Date
	var isNotificationsEnabled: Bool
	var isVerified: Bool
	var allowFriendRequests: Bool
	var showInSuggested: Bool
	var preferredEmojiSkinTone: User.EmojiSkinTone
	var reactionEmojis: [String]
	var quickReaction: String
	var bio: String
	var bioColor: User.BioColor?
	var status: String
	var statusEmoji: String
	var statusTimeout: Date?
	var statusClearValue: User.StatusTimeoutLength?
	var stats: User.Stats
	var supportCode: String
	var invited: Int
	var globalMagicWords: [User.MagicWord]
	var contactHash: String?
	var meetNotifyEnabled: Bool?
	var meetInterests: [String]?
	var meetGender: [User.Gender]?
	var meetNotificationsEnabled: Bool?
	var pronouns: [String]?
	var gender: User.Gender?
	var meetLocation: User.Location?
	var starSign: String?
	var matchRating: Float?
	var allowMatchAudio: Bool
	var allowMatchImages: Bool
	var allowMatchVideos: Bool
	var discoverDisabled: Bool
	var hasAgreedToMeetTerms: Bool
	var hasReducedHonks: Bool
	var teamNotificationsEnabled: Bool
	var streakNotificationsDisabled: Bool
	var hasReducedNotifications: Bool
	var topPicksNotificationEnabled: Bool
	var feelingLuckyNotificationEnabled: Bool
	var badgeCount: Int
	var compliments: [String: Int] // complimentId → count
	var needsConfirmDOB: Bool
	var shouldForceReloadFriends: Bool
	var honkButton: User.HonkButtonCategory
}

extension APIUserInfo {
	init(_ user: User, compliments: [String: Int] = [:], shouldForceReloadFriends: Bool = false) {
		_id = user.id
		firebaseAuthId = user.firebaseUid
		name = user.name
		username = user.username
		avatarURL = user.avatarUrl
		avatarBlurHash = user.avatarBlurHash
		createdAt = user.createdAt
		birthday = user.birthday
		isNotificationsEnabled = user.isNotificationsEnabled
		isVerified = user.isVerified
		allowFriendRequests = user.allowFriendRequests
		showInSuggested = user.showInSuggested
		preferredEmojiSkinTone = user.preferredEmojiSkinTone
		reactionEmojis = user.reactionEmojis
		quickReaction = user.quickReaction
		bio = user.bio
		bioColor = user.bioColor
		status = user.status
		statusEmoji = user.statusEmoji
		statusTimeout = user.statusTimeout
		statusClearValue = user.statusClearValue
		stats = user.stats
		supportCode = user.supportCode
		invited = user.invited
		globalMagicWords = user.globalMagicWords
		contactHash = user.contactHash
		meetNotifyEnabled = user.meetNotifyEnabled
		meetInterests = user.meetInterests
		meetGender = user.meetGender
		meetNotificationsEnabled = user.meetNotificationsEnabled
		pronouns = user.pronouns
		gender = user.gender
		meetLocation = user.meetLocation
		starSign = user.starSign
		matchRating = user.matchRating
		allowMatchAudio = user.allowMatchAudio
		allowMatchImages = user.allowMatchImages
		allowMatchVideos = user.allowMatchVideos
		discoverDisabled = user.discoverDisabled
		hasAgreedToMeetTerms = user.hasAgreedMeetTerms
		hasReducedHonks = user.hasReducedHonks
		teamNotificationsEnabled = user.teamNotificationsEnabled
		streakNotificationsDisabled = user.streakNotificationsDisabled
		hasReducedNotifications = user.hasReducedNotifications
		topPicksNotificationEnabled = user.topPicksNotificationEnabled
		feelingLuckyNotificationEnabled = user.feelingLuckyNotificationEnabled
		badgeCount = user.badgeCount
		self.compliments = compliments
		needsConfirmDOB = user.needsConfirmDOB
		self.shouldForceReloadFriends = shouldForceReloadFriends
		honkButton = user.honkButton
	}
}
